learn/rails/helloworld/config/routes.rb
Helloworld::Application.routes.draw do

  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  get "top/index"

  root :to => 'top#index'  

  resources :message, :only => [:show]

end

learn/rails/helloworld/app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body
end

learn/rails/helloworld/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

learn/rails/helloworld/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

learn/rails/helloworld/app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_filter :authenticate_user!
  def show
    @message = Message.find(params[:id])
  end
end

learn/rails/helloworld/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

learn/rails/helloworld/app/helpers/application_helper.rb
module ApplicationHelper
end

learn/rails/helloworld/app/helpers/message_helper.rb
module MessageHelper
end

learn/rails/helloworld/app/helpers/top_helper.rb
module TopHelper
end

learn/rails/helloworld/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Helloworld
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %p{:style => "float: right;"}
      - if user_signed_in?
        = link_to "logout", destroy_user_session_path, :method => :delete
      - else
        = link_to "login", new_user_session_path
    .notice
      = notice
    .alert
      = alert
    = yield

learn/rails/helloworld/app/views/message/show.html.haml
%p
  = @message.body
%p
  = link_to "top",root_path

learn/rails/helloworld/app/views/top/index.html.haml
%h1 Top#index
%p Find me in app/views/top/index.html.haml
%p
  = link_to "hello message", message_path(1)